### PR TITLE
Added barriers

### PR DESCRIPTION
**Pull request by AnonymousRandomPerson**
Barriers with new physics

### CODE REVIEW

**Comment by AHuynh** [comment]
It looks good so far!
At the moment, occasionally packages can get stuck against the barrier with no way to free them.
Not sure how to reliably recreate the bug yet, but I'll get back to you on it.

**Comment by AnonymousRandomPerson** [comment]
I'm aware of that. I think it has to do with switching the conveyor on the frame that the package is furthest into the barrier. I can look for a fix for now if necessary, but I'll eventually be expanding the "collision" radius to the edges of the packages rather than the centers once those extra physics functions are implemented, which should hopefully make the current problem a non-issue.

**Comment by AnonymousRandomPerson** [comment]
Stuck mail issue should be fixed.

**Comment by jayramafisher** [comment]
I've submitted a pull request to update the physics. It adds a function called cullRectangle, so you can have the barrier affect mail objects that don't have their center directly over the barrier now.

**Comment by AHuynh** [comment]
Apologies for the slow response; attempting to test and merge now.

**Comment by AnonymousRandomPerson** [comment]
I have magnets pretty much ready to go (on the old xml system) besides a minor graphical issue that won't affect testing. Would you prefer I sync them into this PR or hold off and adopt the json system with them first?

**Comment by AHuynh** [comment]
Give me a few more minutes; I almost have the new JSON version I just made updated with your and Jay's changes.

**Comment by AHuynh** [comment]
Okay, take a look at the new push. Right now, it's loading a hard-coded level found in the constructor of ContainerGame to test JSON. It should be easy enough to make your magnets work with the new code. Let me know if you have problems.

**Pull request merged**
